version: '3.3' #Hier wird die Docker Version

services:                                  #Anfang der Service Konfiguration/Definition
   datenbank:                              #Name des ersten Service
     image: mysql:5.7                      #Image per Imagename aufgerufen
     volumes:                              #Volumes definierung
       - db_data:/var/lib/mysql            #Pfad zum Volume
     restart: always                       #Restart argument auf always für immer wieder einen Neustart
     environment:                          #environment variabeln werden gesetzt
       MYSQL_ROOT_PASSWORD: 1234
       MYSQL_DATABASE: wordpress
       MYSQL_USER: bryan
       MYSQL_PASSWORD: 1234

   wordpress:                              #Name des ersten Service
     depends_on:                           #Abhängigkeit zum Datenbank Container erstellen
       - datenbank
     image: wordpress:latest               #Image per Imagename aufgerufen
     ports:                                #Port Exposing
       - "8080:80"
     restart: always                       #Restart argument auf always für immer wieder einen Neustart
     environment:                          #environment variabeln werden gesetzt
       WORDPRESS_DB_HOST: datenbank:3306
       WORDPRESS_DB_USER: bryan
       WORDPRESS_DB_PASSWORD: 1234
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}