version: '3.3' #Hier wird die Docker Version

services:
   datenbank:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 1234
       MYSQL_DATABASE: wordpress
       MYSQL_USER: bryan
       MYSQL_PASSWORD: 1234

   wordpress:
     depends_on:
       - datenbank
     image: wordpress:latest
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: datenbank:3306
       WORDPRESS_DB_USER: bryan
       WORDPRESS_DB_PASSWORD: 1234
       WORDPRESS_DB_NAME: wordpress
volumes:
    db_data: {}